const screens=[["1","Vue d’ensemble","Les loyers, les échéances et les actions prioritaires dans une seule vue."],["2","Tableau de bord des locataires","La situation des locataires en un coup d’œil."],["3","Fiche locataire","Un dossier structuré pour chaque colocataire."],["4","État civil","Les informations du locataire regroupées dans son dossier."],["5","Assurance habitation","Attestation, informations extraites et échéance de renouvellement."],["6","Garanties","Les pièces et informations liées à la garantie du locataire."],["7","Documents du locataire","Les documents associés à chaque dossier."],["8","Baux de location","Les conditions du bail et le suivi de ses documents."],["9","Dépôt de garantie","Le suivi du dépôt dans le parcours locatif."],["10","Tableau de bord des chambres","Une vue des espaces de votre colocation."],["11","Chambres","Les informations de chaque chambre."],["12","Pièces communes","Les espaces partagés regroupés dans votre bien."],["13","Planning d’entretien","Une répartition des tâches par pièce et par locataire."],["14","Revenus et charges","Les encaissements, les dépenses et leur évolution mensuelle."],["15","Revenus","Le détail des revenus locatifs."],["16","Charges","Le détail des dépenses de votre bien."],["17","Documents","Baux, quittances, assurances : une bibliothèque pour retrouver vos pièces."]];

const galleryImage=document.getElementById('gallery-image');
function selectScreen(id){const item=screens.find(s=>s[0]===id);if(!item)return;galleryImage.src='assets/screens/screen-'+id+'.png';galleryImage.alt=item[1];document.getElementById('gallery-title').textContent=item[1];document.getElementById('gallery-description').textContent=item[2];document.querySelectorAll('[data-screen]').forEach(b=>{const active=b.dataset.screen===id;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active))});['gallery-open','gallery-enlarge'].forEach(key=>document.getElementById(key).dataset.screenOpen=id)}
document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>selectScreen(b.dataset.screen)));
document.querySelectorAll('[data-screen-link]').forEach(b=>b.addEventListener('click',()=>selectScreen(b.dataset.screenLink)));
const dialog=document.getElementById('screen-dialog');
document.querySelectorAll('[data-screen-open]').forEach(b=>b.addEventListener('click',()=>{const item=screens.find(s=>s[0]===b.dataset.screenOpen);document.getElementById('dialog-title').textContent=item[1];const image=document.getElementById('dialog-image');image.src='assets/screens/screen-'+item[0]+'.png';image.alt=item[1];dialog.showModal()}));
document.getElementById('dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});document.getElementById('year').textContent=new Date().getFullYear();
